obstacle_range: 3.0
raytrace_range: 3.5

footprint: [[-0.105, -0.11], [-0.105, 0.11], [0.105, 0.11], [0.105, -0.11]]
#robot_radius: 0.110

inflation_radius: 0.3
cost_scaling_factor: 3.0

map_type: costmap
observation_sources: scan
scan: {sensor_frame: sensor_laser, data_type: LaserScan, topic: /m2wr/laser/scan, marking: true, clearing: true}