local_costmap:
  global_frame: odom
  robot_base_frame: link_chassis
  update_frequency: 10.0
  publish_frequency: 10.0

  static_map: false

  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.05

  transform_tolerance: 0.5
inflation_layer:
    enabled: true
    cost_scaling_factor: 10.0

  obstacle_layer:
    enabled: true
    observation_sources: scan
    scan:
      data_type: LaserScan
      topic: /m2wr/laser/scan
      marking: true
      clearing: true